### PR TITLE
Rename csi-opensdsplugin to csi-soda-plugin

### LINKED ISSUE #416: Rename the csi-opensdsplugin to csi-soda-plugin
**Issue/Feature Description:**
Rename the csi-opensdsplugin to csi-soda-plugin

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Since this plugin is vendored by SODA so we need to update the name of the provisioner

### PR DESCRIPTION
**Pull request by asifdxtreme**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
We need this PR to remove the Opensds reference in Provisioner name

**Which issue(s) this PR fixes**:

Fixes #416 

**Test Report Added?**:
 /kind TESTED

### CODE REVIEW

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by sushanthakumar** [comment]
Changes are OK. Docker files , k8s object names (like service etc.) also uses opensds name. I think we can have one issue to update inner level name changes which are not seen at user level

**Comment by sushanthakumar** [comment]
LGTM

**Comment by asifdxtreme** [comment]
> Changes are OK. Docker files , k8s object names (like service etc.) also uses opensds name. I think we can have one issue to update inner level name changes which are not seen at user level

yes @sushanthakumar I observed thoose issues while changing the name, I will be raising another PR with thoose changes

**Review by rajat-soda — APPROVED** [review]
LGTM : Please take care of this  : This branch is out-of-date with the base branch

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
